class RegisterLocations(object):
    NAME = 'input[name="fullName"]'
    CPF = 'input[name="cpf"]'
    EMAIL = 'input[name="email"]'
    WHATSAPP = 'input[name="whatsapp"]'
    POSTAL_CODE = 'input[name="postalcode"]'
    NUMBER = 'input[name="address-number"]'
    DETAILS = 'input[name="address-details"]'
    IMAGE = 'input[accept^="image"]'
    DELIVERY_METHOD = '.delivery-method li'
