class RegisterLocations(object):
    NAME = 'input[name="name"]'
    CPF = 'input[name="cpf"]'
    EMAIL = 'input[name="email"]'
    WHATSAPP = 'input[name="whatsapp"]'
    POSTAL_CODE = 'input[name="postalcode"]'
    NUMBER = 'input[name="address-number"]'
    DETAILS = 'input[name="address-details"]'
    IMAGE = 'input[accept^="image"]'
    DELIVERY_METHOD_MOTO = 'li img[alt="Moto"]'
    DELIVERY_METHOD_BY = 'li img[alt="Bicicleta"]'
    DELIVERY_METHOD_CAR = 'li img[alt="Van/Carro"]'
    BUTTON_SEND = 'form button[type="submit"]'
    BUTTON_SEACHR_CEP = 'input[type="button"][value="Buscar CEP"]'
    TEXT_CONFIRM = 'div[id="swal2-html-container"]'
